# doctrine:
#     orm:
#         auto_generate_proxy_classes: %kernel.debug%
#         auto_mapping: true
#         mappings:
#             translatable:
#                 type: annotation
#                 alias: Gedmo
#                 prefix: Gedmo\Translatable\Entity
#                 # make sure vendor library location is correct
#                 dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"